name: Run Forex Bot

on:
  schedule:
    - cron: '0 2,11 * * *'  # Runs at 4AM and 12am Nigeria time
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python Gold.py
